apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ro5x3z2e5-dotnet-basic
  janus-idp.io/tekton: ro5x3z2e5-dotnet-basic
  backstage.io/kubernetes-id: ro5x3z2e5-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ro5x3z2e5-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
